export enum NotificationType {
  // Order
  ORDER_CREATED = "ORDER_CREATED",
  ORDER_CONFIRMED = "ORDER_CONFIRMED",
  ORDER_PREPARING = "ORDER_PREPARING",
  ORDER_READY_FOR_PICKUP = "ORDER_READY_FOR_PICKUP",
  ORDER_OUT_FOR_DELIVERY = "ORDER_OUT_FOR_DELIVERY",
  ORDER_DELIVERED = "ORDER_DELIVERED",
  ORDER_CANCELLED = "ORDER_CANCELLED",

  // Payment
  PAYMENT_PENDING = "PAYMENT_PENDING",
  PAYMENT_SUCCESS = "PAYMENT_SUCCESS",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  PAYMENT_REFUNDED = "PAYMENT_REFUNDED",

  // Delivery
  RIDER_ASSIGNED = "RIDER_ASSIGNED",
  RIDER_ACCEPTED = "RIDER_ACCEPTED",
  RIDER_REACHED_PICKUP = "RIDER_REACHED_PICKUP",
  RIDER_PICKED_UP = "RIDER_PICKED_UP",
  RIDER_LOCATION_UPDATED = "RIDER_LOCATION_UPDATED",

  // Restaurant
  NEW_ORDER = "NEW_ORDER",
  RESTAURANT_APPROVED = "RESTAURANT_APPROVED",
  RESTAURANT_REJECTED = "RESTAURANT_REJECTED",

  // Delivery Partner
  DELIVERY_PARTNER_APPROVED = "DELIVERY_PARTNER_APPROVED",
  DELIVERY_PARTNER_REJECTED = "DELIVERY_PARTNER_REJECTED",

  // Promotions
  COUPON = "COUPON",
  PROMOTION = "PROMOTION",

  // System
  SYSTEM = "SYSTEM",
}

export enum NotificationChannel {
  SOCKET = "SOCKET",
  PUSH = "PUSH",
  EMAIL = "EMAIL",
  SMS = "SMS",
  IN_APP = "IN_APP",
}

export enum NotificationPriority {
  LOW = "LOW",
  NORMAL = "NORMAL",
  HIGH = "HIGH",
  URGENT = "URGENT",
}

export enum NotificationStatus {
  PENDING = "PENDING",
  SENT = "SENT",
  FAILED = "FAILED",
  READ = "READ",
}

export enum NotificationRecipientType {
  CUSTOMER = "CUSTOMER",
  RESTAURANT = "RESTAURANT",
  DELIVERY_PARTNER = "DELIVERY_PARTNER",
  ADMIN = "ADMIN",
}

export enum NotificationAction {
  OPEN_ORDER = "OPEN_ORDER",
  OPEN_PAYMENT = "OPEN_PAYMENT",
  OPEN_DELIVERY = "OPEN_DELIVERY",
  OPEN_RESTAURANT = "OPEN_RESTAURANT",
  OPEN_PROFILE = "OPEN_PROFILE",
  OPEN_NOTIFICATION = "OPEN_NOTIFICATION",
  NONE = "NONE",
}
